# Generated by Django 2.2 on 2019-04-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_areacoordinates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreaCoordinates',
            new_name='AreaCoordinate',
        ),
    ]
