# Generated by Django 2.2 on 2019-04-16 15:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20190415_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='id',
        ),
        migrations.AddField(
            model_name='problem',
            name='grade',
            field=models.CharField(default='None', max_length=30, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='problem',
            name='mp_url',
            field=models.URLField(default='None', verbose_name='Mountain Project Url'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, size=None, verbose_name='Location Of Climb'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='mp_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.TextField(verbose_name='Problem/Route Name'),
        ),
    ]
