# Generated by Django 2.2 on 2019-04-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20190416_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='gmap_url',
            field=models.URLField(default='None', verbose_name='Google Maps Url'),
        ),
    ]
