# Generated by Django 2.2 on 2019-05-06 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_problem_gmap_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
